services:
  php:
    container_name: seed
    build:
      context: ./docker
      dockerfile: ./seed.Dockerfile
    ports:
      - '9001:9001'
    volumes:
      - ./:/var/seed
  nginx:
    container_name: mirror
    build:
      context: ./docker
      dockerfile: ./mirror.Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./dst/packages:/usr/share/nginx/html
  mysql:
    container_name: mysql
    build:
      context: ./docker
      dockerfile: ./mysql.Dockerfile
    ports:
      - '13306:3306'
